import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "./_components/ui/sonner";
import Footer from "./_components/footer";
import AuthProvider from "./_providers/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FSW Barber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="dark">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/image/favicon2.png" />
        <title>FSW Barber</title>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <main className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <Footer />
          </main>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
